name: CI

on:
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        working-directory: rentalService
        run: chmod +x gradlew

      - name: Build and test with Gradle
        working-directory: rentalService
        run: |
          export SHELL=/bin/bash
          ./gradlew build

      - name: Build and run Docker image
        working-directory: rentalService
        run: |
          export SHELL=/bin/bash
          docker build -t rentalservice .
          docker run -d -p 4000:8080 rentalservice

      - name: Test service endpoint
        run: curl http://localhost:4000/cars
